spring:
  datasource:
    url: ${CLOUD_DB_URL}
    username: ${CLOUD_DB_USERNAME}
    password: ${CLOUD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092
    consumer:
      group-id: alarm-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      notification: alarm-topic


jwt:
  secret: ${JWT_SECRET}

user-service:
  url: ${USER_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  prometheus:
    metrics:
      export:
        enabled: true
