server:
  port: 8000
  forward-headers-strategy: framework

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-service/**
        - id: apigateway-controller
          uri: http://localhost:8000
          predicates:
            - Path=/api/apigateway-service/**

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG