server:
  port: 8000
  forward-headers-strategy: framework

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service.user.svc.cluster.local:8080
          predicates:
            - Path=/api/user-service/**
        - id: summarize-service
          uri: http://summarize-service.summarize.svc.cluster.local:8500
          predicates:
            - Path=/api/summarize-service/**
        - id: matching-service
          uri: http://fastapi-consumer-service.matching.svc.cluster.local:80
          predicates:
            - Path=/api/matching-service/**
        - id: apigateway-health
          uri: forward:/health-check
          predicates:
            - Path=/api/apigateway-service/health-check
          filters:
            - StripPrefix=2

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG