server:
 port: 8000 
 forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081  # ??? EKS??? DNS ??? ??
          predicates:
            - Path=/api/user-service/**  # /user/** ??? ? ???? ??

jwt:
  secret: ${JWT_SECRET}