server:
  port: 8000
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      ignored-paths:
        - /api/apigateway-service/health-check
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-service/**
            
jwt:
  secret: ${JWT_SECRET}