

server:
  port: 8000
  forward-headers-strategy: framework

spring:
  profiles: cloud
  application:
    name: apigateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service.config.svc.cluster.local:8888
      name: apigateway-service
      label: main
      fail-fast: true
    gateway:
      routes:
        - id: health-check
          uri: http://apigateway-service.gateway.svc.cluster.local:8000
          predicates:
            - Path=/api/apigateway-service/health-check
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-service/**

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG