server:
 port: 8000 
 forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      routes:
        - id: self
          uri: http://localhost:8000
          predicates:
            - Path=/api/apigateway-service/health-check
        - id: user-service
          uri: http://localhost:8081  # ??? EKS??? DNS ??? ??
          predicates:
            - Path=/api/user-service/**  # /user/** ??? ? ???? ??

jwt:
  secret: ${JWT_SECRET}