server:
  port: 8000
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      routes:
        - id: self
          uri: http://127.0.0.1:8000
          predicates:
            - Host=a-log.site
            - Path=/api/apigateway-service/health-check

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-service/**
            
jwt:
  secret: ${JWT_SECRET}