spring:
  application:
    name: blog-service

  datasource:
    url: ${CLOUD_DB_URL}
    username: ${CLOUD_DB_USERNAME}
    password: ${CLOUD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver  # (optional, 대부분 auto detect 되지만 명시해도 좋음)
  jpa:
    hibernate:
      ddl-auto: update  # create, update, none 등 상황에 따라
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 로그 보기 좋게 포맷
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # data:
  #   mongodb:
  #     host: ${MONGO_DB_HOST} # ${MONGO_DB_HOST} mongo
  #     port: 27017
  #     authentication-database: admin
  #     database: alog
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
    elasticsearch:
      uris: http://elasticsearch.blog.svc.cluster.local:9200
      # uris: ${ELASTICSEARCH_URIS}
      repositories:
        enabled: true
      connection-timeout: 5s
      socket-timeout: 3s

aws:
  s3:
    bucket: ${S3_BUCKET_NAME} # todo : 임시
    region: ${S3_REGION}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}

feign:
  user-service:
    url : ${FEIGN_USER_SERVICE_URL} #todo : 실제 url 로 바꾸기
  matching-service:
    url : ${FEIGN_MATCHING_SERVICE_URL} #todo : 실제 url 로 바꾸기

springdoc:
  swagger-ui:
    operations-sorter: method

jwt:
  secret: ${JWT_SECRET}
server:
  port: 8030